# Generated by Django 4.2.5 on 2023-09-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='RemoteSensingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('waterlevel', models.PositiveIntegerField()),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydromapp.dam')),
            ],
        ),
        migrations.CreateModel(
            name='RealTimeSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('waterlevel', models.PositiveIntegerField()),
                ('dispatch', models.PositiveIntegerField()),
                ('discharge', models.PositiveIntegerField()),
                ('precipitation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidity', models.PositiveIntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydromapp.dam')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('waterlevel_prediction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydromapp.dam')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=100)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydromapp.dam')),
            ],
        ),
    ]
