# Generated by Django 4.2.5 on 2023-09-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
