# Generated by Django 4.2.5 on 2023-10-22 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0003_alter_dam_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target',
        ),
        migrations.AddField(
            model_name='dam',
            name='active_vol',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='note_msg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='sensor_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dam',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
