# Generated by Django 4.2.5 on 2023-10-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0004_remove_notification_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
