# Generated by Django 4.2.5 on 2023-10-31 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0005_dam_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dam',
            name='slug',
        ),
    ]
