# Generated by Django 4.2.5 on 2023-11-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0007_dam_latitude_dam_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='note_msg',
        ),
        migrations.AddField(
            model_name='notification',
            name='custom_message_above_active',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='custom_message_below_active',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='custom_message_discharge',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
        ),
    ]
