# Generated by Django 4.2.5 on 2023-11-06 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0008_remove_notification_note_msg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sensor_value',
        ),
    ]
