# Generated by Django 4.2.5 on 2023-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0010_notification_custom_message_upstream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='custom_message_upstream',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_email',
            field=models.EmailField(default='paddynsubuga48@gmail.com', max_length=254),
        ),
    ]
