# Generated by Django 4.2.5 on 2023-12-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0011_remove_notification_custom_message_upstream_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_sent',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sensor_value',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_email',
        ),
    ]
