# Generated by Django 4.2.5 on 2024-02-10 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0016_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
