# Generated by Django 4.2.5 on 2024-03-10 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hydromapp', '0019_userprofile_delete_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proifle', to=settings.AUTH_USER_MODEL),
        ),
    ]
