# Generated by Django 5.1.2 on 2025-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0022_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimesensordata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
