# Generated by Django 5.1.2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0023_alter_realtimesensordata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamPrecipitationState',
            fields=[
                ('dam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hydromapp.dam')),
                ('last_cumulative', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='realtimesensordata',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, help_text='Precipitation delta in mm (distinct value per interval)', max_digits=10),
        ),
    ]
