# Generated by Django 5.2.14 on 2026-07-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0026_waterlevel_three_decimals'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('department', models.CharField(blank=True, max_length=160)),
                ('area', models.CharField(max_length=120)),
                ('priority', models.CharField(choices=[('low', 'Low - suggestion'), ('normal', 'Normal - improvement'), ('high', 'High - affects work'), ('critical', 'Critical - urgent issue')], default='normal', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
