# Generated by Django 5.2.14 on 2026-07-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydromapp', '0028_reservoir_head_tail_waterlevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('partial', 'Partial data'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('completeness_percent', models.PositiveSmallIntegerField(default=0)),
                ('dams_covered', models.PositiveSmallIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('missing_data_highlights', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, upload_to='system_reports/')),
                ('narrative_provider', models.CharField(blank=True, default='template', max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-period_end', '-generated_at', '-id'],
                'unique_together': {('period_type', 'period_start', 'period_end')},
            },
        ),
    ]
