"""
Django settings for hydromapp project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from decouple import Csv, Config, RepositoryEnv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load secrets from project-root .env (next to manage.py)
from decouple import config as default_config

_env_file = BASE_DIR / '.env'
_env_example = BASE_DIR / '.env.example'
if _env_file.exists():
    config = Config(RepositoryEnv(str(_env_file)))
elif _env_example.exists():
    config = Config(RepositoryEnv(str(_env_example)))
else:
    # Fall back to process environment if no dotenv file is present yet.
    config = default_config


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY')
# Default DEBUG to False on Railway so POST/login errors return JSON, not an HTML traceback.
_on_railway = bool(os.environ.get('RAILWAY_ENVIRONMENT') or os.environ.get('RAILWAY_PROJECT_ID'))
DEBUG = config('DEBUG', default=not _on_railway, cast=bool)


def _csv_values(name, default):
    raw = os.environ.get(name)
    if raw is None or str(raw).strip() == '':
        raw = config(name, default=default)
    if isinstance(raw, (list, tuple)):
        return [str(item).strip() for item in raw if str(item).strip()]
    return [part.strip() for part in str(raw).split(',') if part.strip()]


def _hostname(value):
    text = (value or '').strip()
    if not text:
        return ''
    text = text.replace('https://', '').replace('http://', '').split('/')[0]
    return text.split(':')[0].strip().lstrip('.')


ALLOWED_HOSTS = _csv_values('ALLOWED_HOSTS', 'localhost,127.0.0.1')
CSRF_TRUSTED_ORIGINS = _csv_values(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:5173,http://127.0.0.1:5173',
)

# Always allow the live Hydro-M domains so login POSTs are not blocked by
# a missing Railway variable or a Docker build-time CSRF_TRUSTED_ORIGINS.
_extra_hosts = [
    'hydrom-ug.com',
    'www.hydrom-ug.com',
    '.up.railway.app',
    _hostname(os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')),
    _hostname(os.environ.get('RAILWAY_STATIC_URL', '')),
]
for host in _extra_hosts:
    if host and host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

_extra_origins = [
    'https://hydrom-ug.com',
    'https://www.hydrom-ug.com',
    'https://*.up.railway.app',
]
_public_host = _hostname(os.environ.get('RAILWAY_PUBLIC_DOMAIN', ''))
if _public_host:
    _extra_origins.append(f'https://{_public_host}')
for origin in _extra_origins:
    if origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

# Railway terminates TLS at the proxy. Without this, CSRF can reject HTTPS POSTs.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
# Allow the React SPA to read the CSRF cookie for fetch() POSTs.
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_FAILURE_VIEW = 'hydromapp.auth_api.csrf_failure'

# Public site URL used in emails/links when needed (optional).
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL') or config('FRONTEND_BASE_URL', default='')

# Device ingest API key
API_KEY = config('API_KEY', default='')


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'hydromapp.apps.HydromappConfig',
]

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hydromapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'hydromapp.context_processors.notification_processor',
                'hydromapp.context_processors.dams_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'hydromapp.wsgi.application'
ASGI_APPLICATION = 'hydromapp.asgi.application'


# Database
# Prefer Railway/runtime env over a local .env file.
# Local development: use SQLite when DATABASE_URL is empty.
DATABASE_URL = os.environ.get('DATABASE_URL') or config('DATABASE_URL', default='')

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = True
USE_TZ = True


# Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Compressed (not Manifest): Vite already content-hashes its assets.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Built Vite SPA (web/ → static/frontend/)
FRONTEND_INDEX = BASE_DIR / 'static' / 'frontend' / 'index.html'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Media files (assistant-generated reports, uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Hydro-M Assistant / OpenAI
OPENAI_API_KEY = config('OPENAI_API_KEY', default='')
OPENAI_MODEL = config('OPENAI_MODEL', default='gpt-4o-mini')

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='') or EMAIL_HOST_USER or 'noreply@hydrom.local'

# Celery configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = config('CELERY_TIMEZONE', default='Africa/Nairobi')

try:
    from celery.schedules import crontab

    CELERY_BEAT_SCHEDULE = {
        'generate-weekly-system-report': {
            'task': 'hydromapp.generate_weekly_system_report',
            # Mondays 06:00 Africa/Nairobi
            'schedule': crontab(minute=0, hour=6, day_of_week=1),
        },
        'generate-monthly-system-report': {
            'task': 'hydromapp.generate_monthly_system_report',
            # 1st of month 06:15 Africa/Nairobi
            'schedule': crontab(minute=15, hour=6, day_of_month=1),
        },
    }
except Exception:  # noqa: BLE001
    CELERY_BEAT_SCHEDULE = {}
